### ISSUE TITLE
Make performed at date selectable

### ISSUE THREAD

**Issue by pawegio** [elpassion/el-peon-android#20]
I would like to click on a date below "Performed At" label, then see a dialog with calendar view component and select a different date.

**Comment by jozzi05** [comment]
This library looks great! 

But, on ReportAddActivity when december is selected, on the screen is shown wrong month (selected_month - 1)

Futhermore on ReportEditActivity date does not change at all.

It would be nice also to set date at the start to the same date as currently selected.

**Comment by pawegio** [comment]
Looks nice, but it is also now missing an arrow icon on the right indicating that date can be changed.
