### ISSUE TITLE
create tasks for api

### ISSUE THREAD

**Issue by jozzi05** [elpassion/el-peon-android#41]

**Comment by ghostbuster91** [comment]
https://github.com/elpassion/hub/issues

**Comment by jozzi05** [comment]
https://elpassion.atlassian.net/secure/RapidBoard.jspa?rapidView=4&projectKey=HUB

**Comment by ghostbuster91** [comment]
https://elpassion.atlassian.net/secure/RapidBoard.jspa?rapidView=4&projectKey=HUB&selectedIssue=HUB-10
